config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :parkinghouses do
    resources :comments
    resources :cars
  end
  resources :cars
  devise_for :users

  root 'parkinghouses#index'

end

app/controllers/parkinghouses_controller.rb
class ParkinghousesController < ApplicationController
  before_action :set_parkinghouse, only: [:show, :edit, :update, :destroy]

  # GET /parkinghouses
  # GET /parkinghouses.json
  def index
    @parkinghouses = Parkinghouse.all
    @count = 0
  end

  # GET /parkinghouses/1
  # GET /parkinghouses/1.json
  def show
    @comment = Comment.new parkinghouse: @parkinghouse
    
    @car = Car.new parkinghouse: @parkinghouse
    2.times { @car.car_images.build}
  end

  # GET /parkinghouses/new
  def new
    @parkinghouse = Parkinghouse.new
  end

  # GET /parkinghouses/1/edit
  def edit
  end

  # POST /parkinghouses
  # POST /parkinghouses.json
  def create
    @parkinghouse = Parkinghouse.new(parkinghouse_params)

    respond_to do |format|
      if @parkinghouse.save
        format.html { redirect_to @parkinghouse, notice: 'Parkinghouse was successfully created.' }
        format.json { render :show, status: :created, location: @parkinghouse }
      else
        format.html { render :new }
        format.json { render json: @parkinghouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parkinghouses/1
  # PATCH/PUT /parkinghouses/1.json
  def update
    respond_to do |format|
      if @parkinghouse.update(parkinghouse_params)
        format.html { redirect_to @parkinghouse, notice: 'Parkinghouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @parkinghouse }
      else
        format.html { render :edit }
        format.json { render json: @parkinghouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkinghouses/1
  # DELETE /parkinghouses/1.json
  def destroy
    @parkinghouse.destroy
    respond_to do |format|
      format.html { redirect_to parkinghouses_url, notice: 'Parkinghouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parkinghouse
      @parkinghouse = Parkinghouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parkinghouse_params
      params.require(:parkinghouse).permit(:name, :address, :description, :image, :car_images_attributes)
    end
end

app/helpers/parkinghouses_helper.rb
module ParkinghousesHelper
end

app/views/parkinghouses/_car.html.haml
%div
	%h4 Rendszám:
	=car.plate
	%p Utolsó látogatás:
	=car.lastvisit
	%p Szín
	=car.color
	%p
	=car.licence

app/views/parkinghouses/_comment.html.haml
%div
	%h4 Comment by 
	=comment.user_name
	%p
		=comment.body

app/views/parkinghouses/_form.html.haml
= form_for @parkinghouse do |f|
  - if @parkinghouse.errors.any?
    #error_explanation
      %h2= "#{pluralize(@parkinghouse.errors.count, "error")} prohibited this parkinghouse from being saved:"
      %ul
        - @parkinghouse.errors.full_messages.each do |msg|
          %li= msg
  %form{ :role => "form" }
    .form-group
      = f.label :name, "Név: "
      = f.text_field :name, :class => "form-control"
    .form-group
      = f.label :address, "Cím: "
      = f.text_field :address, :class => "form-control"
    .form-group
      = f.label :description, "Leírás :"
      = f.text_area :description, :class => "form-control"
    .form-group
      = f.label :image, "Kép feltölés: "
      = f.file_field :image
    .actions
      = f.submit 'Save', :class => "btn btn-success"

app/views/parkinghouses/edit.html.haml
%h1 Editing parkinghouse

= render 'form'

= link_to 'Show', @parkinghouse
\|
= link_to 'Back', parkinghouses_path

app/views/parkinghouses/index.html.haml
%h1 Listing parkinghouses
.row
  - @parkinghouses.each do |parkinghouse|
    %div{ :class => "col-md-4 col-sm-6 col-xs-12 text-center" }
      =link_to parkinghouse, :class => "thumbnail" do
        =image_tag parkinghouse.image.url(:main) if parkinghouse.image.exists?   
      %h4=parkinghouse.name
      %p=parkinghouse.address
      %p=parkinghouse.description
      - if can? :update, parkinghouse
        =link_to 'Edit', edit_parkinghouse_path(parkinghouse)
      - if can? :destroy, parkinghouse
        = link_to 'Destroy', parkinghouse, :method => :delete, :data => { :confirm => 'Are you sure?' } 
        

app/views/parkinghouses/new.html.haml
%h1 New parkinghouse

= render 'form'

= link_to 'Back', parkinghouses_path

app/views/parkinghouses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @parkinghouse.name
%p
  %b Address:
  = @parkinghouse.address
%p
  %b Description:
  = @parkinghouse.description
%p
  %b Image:
  = link_to @parkinghouse.image.url do
    =image_tag @parkinghouse.image.url(:thumbnail)
%h3 Komment:
=render partial: 'parkinghouses/comment', collection: @parkinghouse.comments

=render partial: 'parkinghouses/car', collection: @parkinghouse.cars

=render partial: 'cars/form'

=render partial: 'comments/form' if user_signed_in?


= link_to 'Edit', edit_parkinghouse_path(@parkinghouse)
\|
= link_to 'Back', parkinghouses_path